# Generated from schema.json — do not edit by hand.
# BIDS version 1.10.0
from enum import Enum
from .. import Schema as SchemaBase

class DatatypeEnum(Enum):
    anat = ...
    beh = ...
    dwi = ...
    eeg = ...
    fmap = ...
    func = ...
    ieeg = ...
    meg = ...
    micr = ...
    motion = ...
    mrs = ...
    perf = ...
    pet = ...
    nirs = ...

class ModalityEnum(Enum):
    mri = ...
    eeg = ...
    ieeg = ...
    meg = ...
    beh = ...
    pet = ...
    micr = ...
    motion = ...
    nirs = ...
    mrs = ...

class SuffixEnum(Enum):
    TwoPE = ...
    BF = ...
    Chimap = ...
    CARS = ...
    CONF = ...
    DIC = ...
    DF = ...
    FLAIR = ...
    FLASH = ...
    FLUO = ...
    IRT1 = ...
    M0map = ...
    MEGRE = ...
    MESE = ...
    MP2RAGE = ...
    MPE = ...
    MPM = ...
    MTR = ...
    MTRmap = ...
    MTS = ...
    MTVmap = ...
    MTsat = ...
    MWFmap = ...
    NLO = ...
    OCT = ...
    PC = ...
    PD = ...
    PDT2 = ...
    PDmap = ...
    PDw = ...
    PLI = ...
    R1map = ...
    R2map = ...
    R2starmap = ...
    RB1COR = ...
    RB1map = ...
    S0map = ...
    SEM = ...
    SPIM = ...
    SR = ...
    T1map = ...
    T1rho = ...
    T1w = ...
    T2map = ...
    T2star = ...
    T2starmap = ...
    T2starw = ...
    T2w = ...
    TB1AFI = ...
    TB1DAM = ...
    TB1EPI = ...
    TB1RFM = ...
    TB1SRGE = ...
    TB1TFL = ...
    TB1map = ...
    TEM = ...
    UNIT1 = ...
    VFA = ...
    angio = ...
    asl = ...
    aslcontext = ...
    asllabeling = ...
    beh = ...
    blood = ...
    bold = ...
    cbv = ...
    channels = ...
    coordsystem = ...
    defacemask = ...
    descriptions = ...
    dseg = ...
    dwi = ...
    eeg = ...
    electrodes = ...
    epi = ...
    events = ...
    fieldmap = ...
    headshape = ...
    XPCT = ...
    ieeg = ...
    inplaneT1 = ...
    inplaneT2 = ...
    m0scan = ...
    magnitude = ...
    magnitude1 = ...
    magnitude2 = ...
    markers = ...
    mask = ...
    meg = ...
    motion = ...
    mrsi = ...
    mrsref = ...
    nirs = ...
    noRF = ...
    optodes = ...
    pet = ...
    phase = ...
    phase1 = ...
    phase2 = ...
    phasediff = ...
    photo = ...
    physio = ...
    probseg = ...
    sbref = ...
    scans = ...
    sessions = ...
    stim = ...
    svs = ...
    uCT = ...
    unloc = ...

class EntityEnum(Enum):
    subject = ...
    session = ...
    sample = ...
    task = ...
    tracksys = ...
    acquisition = ...
    nucleus = ...
    volume = ...
    ceagent = ...
    tracer = ...
    stain = ...
    reconstruction = ...
    direction = ...
    run = ...
    modality = ...
    echo = ...
    flip = ...
    inversion = ...
    mtransfer = ...
    part = ...
    processing = ...
    hemisphere = ...
    space = ...
    split = ...
    recording = ...
    chunk = ...
    segmentation = ...
    resolution = ...
    density = ...
    label = ...
    description = ...

class Schema(SchemaBase):
    DatatypeEnum: type[DatatypeEnum]
    ModalityEnum: type[ModalityEnum]
    SuffixEnum: type[SuffixEnum]
    EntityEnum: type[EntityEnum]
